Repository Meet-Coder-Study/book-software-architecture-101, pull requests merged in 2022-03, with the labels that each got.

#11 [3주차] Chapter 4. 아키텍처 특성 정의
  04장/[3주차]_4장_아키텍처_특성_정의_김석래.md
  04장/images/001.png
  04장/images/002.png
  04장/images/003.png
  04장/images/004.png
  04장/images/triangle.png
Labels: 1.4 아키텍처 특성 정의, 3주차

#14 [3주차] Chapter 5. 아키텍처 특성 식별
  05장/[3주차]_5장_아키텍처_특성_식별_이호경.md
  05장/empty.txt
  05장/images/5_1.jpeg
  05장/images/5_2.jpeg
Labels: 1.5 아키텍처 특성 식별, 3주차

#15 [4주차] Chapter 6. 아키텍쳐 특성의 측정 및 거버넌스
  06장/[4주차]_6장_아키텍쳐_특성의_측정_및_거버넌스_황준호.md
Labels: 1.6 아키텍처 특성의 측정 및 거버넌스, 4주차

#18 [5주차] Chapter 8. 컴포넌트 기반 사고
  08장/empty.txt
  08장/컴포넌트_기반_사고_김나은.md
Labels: 1.8 컴포넌트 기반 사고, 5주차

#21 [5주차] Chapter 9. 아키텍처 스타일 기초
  .github/workflows/automerge.yml
  09장/[5주차]_9장_아키텍처_스타일_기초.md
  09장/images/001.png
  09장/images/002.png
  09장/images/003.png
  09장/images/004.png
  09장/images/005.png
  09장/images/006.png
  09장/images/007.png
  09장/images/008.png
  09장/images/009.png
  09장/images/010.png
  09장/images/011.png
  09장/images/012.png
Labels: 2.9 아키텍처 스타일 기초, 5주차

#23 [6주차] Chapter 11. 파이프라인 아키텍처 스타일
  11장/[6주차]_11장_파이프라인_아키텍쳐_스타일_황준호.md
  images/pipeline_architecture.jpeg
  images/pipeline_architecture_example.jpeg
Labels: 2.11 파이프라인 아키텍처 스타일, 6주차
