Repository Meet-Coder-Study/book-software-architecture-101, pull requests merged in 2022-04, with the labels that each got.

#31 [8주차] 2.14 이벤트 기반 아키텍처 스타일
  14장/[8주차]_14장_이벤트_기반_아키텍처_스타일_김석래.md
  14장/images/001.png
  14장/images/002.png
  14장/images/003.png
  14장/images/004.png
  14장/images/005.png
  14장/images/006.png
  14장/images/007.png
  14장/images/008.png
  14장/images/009.png
  14장/images/010.png
  14장/images/011.png
  14장/images/012.png
  14장/images/013.png
  14장/images/014.png
  14장/images/015.png
  14장/images/016.png
  14장/images/017.png
  14장/images/018.png
  14장/images/019.png
  14장/images/020.png
  14장/images/021.png
  14장/images/022.png
Labels: 2.14 이벤트 기반 아키텍처 스타일, 8주차

#40 [9주차] Chapter 16. 오케스트레이션 기반 서비스 지향 아키텍쳐 스타일
  16장/[9주차]_16장_오케스트레이션_기반_서비스_지향_아키텍쳐_스타일_황준호.md
  images/service_oriented_architecture_topology.jpg
Labels: 2.16 오케스트레이션 기반 서비스 지향 아키텍처 스타일, 9주차

#37 [10주차] 아키텍처 결정
  19장/[10주차]_19장_아키텍처_결정_김석래.md
  19장/images/001.png
  19장/images/002.png
  19장/images/003.png
  19장/images/004.png
Labels: 3.19 아키텍처 결정, 10주차

#43 [11주차] 최적의 아키텍처 스타일 선정
  18장/18장_최적의_아키텍처_스타일_선정.md
Labels: 2.18 최적의 아키텍처 스타일 선정, 11주차

#41 [11주차] 아키텍처 리스크 분석
  20장/20장_아키텍처_리스크_분석.md
  20장/images/001.png
  20장/images/002.png
  20장/images/003.png
  20장/images/004.png
  20장/images/005.png
  20장/images/006.png
  20장/images/007.png
  20장/images/008.png
  20장/images/009.png
  20장/images/010.png
  20장/images/011.png
  20장/images/012.png
Labels: 3.20 아키텍처 리스크 분석, 11주차
